# Generated by Django 2.1.1 on 2018-10-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mobile', models.IntegerField()),
                ('user_message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
