# Generated by Django 2.1.1 on 2018-10-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0003_auto_20181028_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_send',
            name='user_mobile',
            field=models.CharField(max_length=15),
        ),
    ]
