# Generated by Django 2.1.1 on 2018-10-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0005_debit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='debit',
        ),
    ]
