# Generated by Django 2.1.1 on 2018-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0006_delete_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40)),
                ('User_Comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='message_send',
        ),
        migrations.RemoveField(
            model_name='user_information',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_information',
            name='User_Name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
