# Generated by Django 2.1.1 on 2018-11-18 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0007_auto_20181112_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_send',
            name='Current_Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
