# Generated by Django 2.1.1 on 2018-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0008_comment_send_current_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40)),
                ('User_Comment_ID', models.IntegerField()),
            ],
        ),
    ]
