# Generated by Django 2.1.1 on 2018-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0009_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40)),
                ('User_Comment_ID', models.IntegerField()),
                ('User_Comment_Post', models.CharField(max_length=1000)),
            ],
        ),
    ]
