# Generated by Django 2.1.1 on 2018-11-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0010_comment_save'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment_send',
            new_name='first_level_comment',
        ),
        migrations.RenameModel(
            old_name='like',
            new_name='first_level_like',
        ),
        migrations.RenameModel(
            old_name='comment_save',
            new_name='second_level_comment',
        ),
    ]
